### ISSUE TITLE
Test suite fails (with older Map::Tube?)

### ISSUE THREAD

**Issue by eserte** [mfontani/Map-Tube-Milan#2]
On some of my smokers I see the following failure:
```
Can't apply Map::Tube to Map::Tube::Milan - missing xml at /opt/perl-5.20.0/lib/site_perl/5.20.0/Moo/Role.pm line 287.
Compilation failed in require at t/03-map.t line 5.
BEGIN failed--compilation aborted at t/03-map.t line 5.
t/03-map.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```
Probably it fails because an older version of Map::Tube is installed here (3.18). With 3.41 and 3.42 the test suite passes. So probably the minimum version in PREREQ_PM should be adjusted.

**Comment by mfontani** [comment]
Thank you for that; I noticed the same and did a little digging.

I think I've found the minimum version of Map::Tube this module requires, and I've released a new version to CPAN. If this all goes well, I'll close this issue.

**Comment by mfontani** [comment]
http://matrix.cpantesters.org/?dist=Map-Tube-Milan shows me that this problem has indeed now been fixed. Thanks again for alerting me of it.
